version = 1

[[annotations]]
path = [
    ".gas-snapshot",
    ".github/workflows/**/",
    "meta/**/",
    ".gitignore",
    ".gitmodules",
    "README.md",
    "flake.lock",
    "flake.nix",
    "foundry.toml",
    "slither.config.json",
    "REUSE.toml",
    "package-lock.json",
    "package.json",
    "test/proof/**/",
    "foundry.lock",
]
SPDX-FileCopyrightText = "Copyright (c) 2020 Rain Open Source Software Ltd"
SPDX-License-Identifier = "LicenseRef-DCL-1.0"
